version: 2.1

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: cimg/node:16.16.0

jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-configuration-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Set npmrc credentials
          command: echo -e $NPMRC > ~/.npmrc
      - run:
          name: Install dependencies
          command: "[ -d node_modules ] || npm i"
      - save_cache:
          key: dependency-configuration-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-configuration-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Build package
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Test code
          command: npm t
      - store_test_results:
          path: test-results
  lint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Lint
          command: npm run lint


workflows:
  ci-cd:
    jobs:
      - dependencies:
          context: org-global
      - build:
          context: org-global
          requires:
            - dependencies
      - lint:
          context: org-global
          requires:
            - build
      - test:
          context: org-global
          requires:
            - build
